.\" Manpage for DamOS Client program.
.\" Contact puckowski.d@gmail.com to correct errors or typos.

.TH man 8 "05 April 2014" "1.2" "DamOS Client man page"

.SH NAME
DamOS Client \- When this software is installed and executed on a system, it may be used
as a messenger between a command-and-control (C&C) server and its host system.

.SH SYNOPSIS
DamOS Client Program

Setup of the program is simple. Example usage is as follows:

./client 127.0.0.1 5560

The program only needs an IP address and a port number to connect to.

.SH DESCRIPTION
DamOS Client Program

This program may be used to collect data being processed on its host system
and then, periodically, send that data to a C&C server.

This program may also receive executables from a C&C server and may execute tasks at the 
C&C server's direction. 

.SH OPTIONS

None.

.SH SEE ALSO

DamOS C&C Server Program.

.SH BUGS

No known bugs.

.SH AUTHOR

Daniel Puckowski (puckowski.d@gmail.com)
