.\" Manpage for DamOS Linux Keystroke Logger.
.\" Contact puckowski.d@gmail.com to correct errors or typos.

.TH man 8 "05 April 2014" "1.0" "DamOS Linux Keystroke Logger man page"

.SH NAME
Linux Keystroke Logger \- This program may be used to log keystroke data for a specific keyboard device on a Linux system.

.SH SYNOPSIS
Linux Keystroke Logger 

Example program usage:

./logger /dev/input/event2 logger_output.txt

.SH OPTIONS

None.

.SH SEE ALSO

DamOS Linux Log Processor

.SH BUGS


No known bugs.

.SH AUTHOR

Daniel Puckowski (puckowski.d@gmail.com)
