.\" Manpage for DamOS Linux Log Processor.
.\" Contact puckowski.d@gmail.com to correct errors or typos.

.TH man 8 "05 April 2014" "1.0" "DamOS Linux Log Processor man page"

.SH NAME
DamOS Linux Log Processor \- This program will process keystroke log data
collected by the DamOS Linux Keystroke Logger Program.

.SH SYNOPSIS
DamOS Linux Log Processor 

Example usage is as follows:

./processor output_file.txt

.SH OPTIONS

None.

.SH SEE ALSO

DamOS Linux Keystroke Logger

.SH BUGS

No known bugs.

.SH AUTHOR

Daniel Puckowski (puckowski.d@gmail.com)
