.\" Manpage for DamOS Menu Reader Program.
.\" Contact puckowski.d@gmail.com to correct errors or typos.

.TH man 8 "05 April 2014" "1.0" "DamOS Menu Reader Program man page"

.SH NAME
DamOS Menu Reader Program \- This program will read a formatted menu file and 
print an interactive text-menu in a terminal.

.SH SYNOPSIS
DamOS Menu Reader Program

Example usage is as follows:

./reader menu_file.txt

.SH OPTIONS

None.

.SH SEE ALSO

None.

.SH BUGS

No known bugs.

.SH AUTHOR

Daniel Puckowski (puckowski.d@gmail.com)
